<a href="https://colab.research.google.com/github/Felipe-DelosSantos09/Diplomado-IA/blob/master/Apertura_de_ventanas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [3]:
# cargamos las 7 combinaciones de las compuertas XOR
training_data = np.array([[0,0,0,0],[1,0,0,0],[1,0,1,0],
 [1,0,0,1],[0,1,0,0],[0,1,1,0],[0,1,0,1]])

# y estos son los resultados que se obtienen, en el mismo orden
target_data = np.array([[[0],[0],[1],[0],[0],[0],[1],[0]],[[1],[0],[0],[0],[1],[0],[0],[0]],
 [[0],[0],[0],[0],[0],[0],[0],[0]],[[0],[1],[0],[0],[0],[0],[1],[0]],
[[0],[0],[0],[1],[0],[0],[0],[1]],[[0],[0],[0],[1],[0],[0],[1],[0]],
[[0],[0],[1],[0],[0],[0],[0],[1]]])

In [4]:
print(target_data)

[[[0]
  [0]
  [1]
  [0]
  [0]
  [0]
  [1]
  [0]]

 [[1]
  [0]
  [0]
  [0]
  [1]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [1]
  [0]
  [0]
  [0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [0]
  [1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]
  [0]
  [0]
  [1]]]


In [5]:
print(training_data)

[[0 0 0 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 0 0]
 [0 1 1 0]
 [0 1 0 1]]


# Definimos una arquitectura de red neuronal

In [11]:
model = Sequential()
model.add(Dense(20, input_dim=4, activation='relu'))
model.add(Dense(40, input_dim=4, activation='relu'))
model.add(Dense(8, activation='sigmoid'))

In [12]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

# Entrenamiento de la red

In [13]:
model.fit(training_data, target_data, epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 813ms/step - loss: 0.2393 - binary_accuracy: 0.6250
Epoch 2/500
1/1 [==============================] - 0s 12ms/step - loss: 0.2378 - binary_accuracy: 0.6607
Epoch 3/500
1/1 [==============================] - 0s 14ms/step - loss: 0.2364 - binary_accuracy: 0.6607
Epoch 4/500
1/1 [==============================] - 0s 12ms/step - loss: 0.2349 - binary_accuracy: 0.6786
Epoch 5/500
1/1 [==============================] - 0s 12ms/step - loss: 0.2335 - binary_accuracy: 0.6786
Epoch 6/500
1/1 [==============================] - 0s 16ms/step - loss: 0.2320 - binary_accuracy: 0.6786
Epoch 7/500
1/1 [==============================] - 0s 14ms/step - loss: 0.2305 - binary_accuracy: 0.6786
Epoch 8/500
1/1 [==============================] - 0s 13ms/step - loss: 0.2291 - binary_accuracy: 0.6429
Epoch 9/500
1/1 [==============================] - 0s 13ms/step - loss: 0.2276 - binary_accuracy: 0.6429
Epoch 10/500
1/1 [==============================] - 0s

In [9]:
# evaluamos el modelo
scores = model.evaluate(training_data, target_data)

1/1 [==============================] - 0s 217ms/step - loss: 0.0714 - binary_accuracy: 0.9286


In [14]:

print (model.predict(training_data).round())

1/1 [==============================] - 0s 77ms/step
[[0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]
